:sparkles: Update template
Les-Cop1/template-express-react pull request #23
Opened 2022-11-11 13:34 UTC by FelixLgr

2022-11-11 13:51 UTC, LucasStbnr requested changes

2022-11-11 13:51 UTC, LucasStbnr commented on back/.eslintignore
> +craco.config.js
Craco dans le back ?

2022-11-11 13:51 UTC, LucasStbnr commented on back/.eslintrc
> +    "react-app/jest",
React aussi dans la back ?

2022-11-11 13:51 UTC, LucasStbnr commented on back/package.json
> +        "format": "prettier --write '**/*.{js,jsx,ts}'",
jsx ?

2022-11-11 13:51 UTC, LucasStbnr commented on back/src/controllers/user.ts
> +  let validations = []
const

2022-11-11 13:51 UTC, LucasStbnr commented on back/src/types/category.ts
> +export interface ICategory extends Document {
Catégorie ?

2022-11-11 13:51 UTC, LucasStbnr commented on back/src/types/file.ts
> +}
Pourquoi la gestion des fichiers dans le template ?

2022-11-11 13:51 UTC, LucasStbnr commented on back/src/types/item.ts
> +}
C'est mysetup ou un template ?

2022-11-11 13:51 UTC, LucasStbnr commented on back/src/types/room.ts
> +}
Toujours pareil

2022-11-11 21:31 UTC, LucasStbnr commented on .env-example
> +MONGO_URL=""
C'est mieux .env.example

2022-11-11 21:33 UTC, LucasStbnr commented on back/.gitignore
> +coverage.txt
Pourquoi 2 .gitignore ?

2022-11-11 21:34 UTC, LucasStbnr commented on back/src/helpers/authenticated.ts
> +    // eslint-disable-next-line security/detect-possible-timing-attacks
?

2022-11-11 21:35 UTC, LucasStbnr commented on back/src/routes/user.ts
> +  } catch (error: any) {
Faut faire quelque chose, on va pas mettre l'exception à la règle partout

2022-11-11 21:37 UTC, LucasStbnr approved these changes

2022-11-11 21:37 UTC, merged

2022-11-12 13:46 UTC, FelixLgr commented on back/src/helpers/authenticated.ts
> +    // eslint-disable-next-line security/detect-possible-timing-attacks
c'est le lint qui me dit :  Potential timing attack, left side: true  security/detect-possible-timing-attacks
j'avoue que je vois pas trop pourquoi