:heavy_plus_sign: add express-rate-limit
Les-Cop1/template-express-react pull request #32
Opened 2022-11-12 21:52 UTC by FelixLgr

2022-11-12 22:57 UTC, LucasStbnr requested changes
Merci de bien utiliser la librairie

2022-11-12 22:57 UTC, LucasStbnr commented on back/src/app.ts
> +})
Il s'agirait de regarder comment la librairie fonctionne

var RateLimit = require('express-rate-limit');
var limiter = new RateLimit({
  windowMs: 1*60*1000, // 1 minute
  max: 5
});

2022-11-12 22:57 UTC, LucasStbnr commented on back/src/app.ts
> +  max: 100, // Limit each IP to 100 requests per 5 minutes
Tu t'es basé sur quoi pour 100 requêtes en 5 min ?

2022-11-13 18:23 UTC, FelixLgr commented on back/src/app.ts
> +})
Effectivement tu as raison.
C'est pourquoi je l'ai déjà fait : https://www.npmjs.com/package/express-rate-limit#examples

2022-11-13 18:25 UTC, FelixLgr commented on back/src/app.ts
> +  max: 100, // Limit each IP to 100 requests per 5 minutes
ca je savais pas je me suis dit que 100 en 15 minutes (d'après ce qu'ils proposent) ca faisait pas beaucoup et je me suis dit que 100 en 10 minutes c'était peut être pas assez non plus

2023-01-27 21:45 UTC, LucasStbnr approved these changes

2023-01-27 21:45 UTC, merged